#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
image=secretflow/authmanager-ubuntu-ci:0.1.0b
DOCKER=docker
project=authmanager
if [[ $1 == 'enter' ]]; then
    sudo $DOCKER exec -it ${project}-build-ubuntu-$(whoami)-sgx2 bash
else
    sudo $DOCKER run --name ${project}-build-ubuntu-$(whoami)-sgx2 -td \
        --net host \
        -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision \
        -v $DIR:/home/admin/dev \
        -v /root/${USER}-${project}-bazel-cache-test:/root/.cache/bazel \
        -w /home/admin/dev \
        --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
        --cap-add=NET_ADMIN \
        --privileged=true \
        ${image}
fi
